### ISSUE TITLE
Wrong Icon?

### ISSUE THREAD

**Issue by Rebel459** [22858/ns-fd-rc#1]
Hi there!
Love the Nature’s Spirit FD recipe compat addon you made, and in checking it out I noticed that you seemed to have used Nature’s Melody’s icon in your icon, rather than Nature’s Spirit’s. Not sure if this is intentional, and it’s certainly not a notable issue, but thought I’d bring it to your attention as it seemed a bit strange. 
I’ve also attached an image to show you what I mean, visually.
![D7FD7F91-0E2C-44D3-865A-B23D4AF91B29](https://github.com/22858/ns-fd-rc/assets/131760345/daae8c8b-9a4e-44f0-955f-9d169a0b6272)

**Comment by 22858** [comment]
The icon was made in a hurry and I failed to notice that.
Extremely sorry for the terrible mistake😭😭

**Comment by 22858** [comment]
![pack](https://github.com/22858/ns-fd-rc/assets/153057608/e4ccb8ec-f7e7-4df2-bacf-8526eb5000fa)
now the icon is the right one

**Comment by Rebel459** [comment]
Don’t worry about it lol, no need to apologise :)
Thanks again for your time and for making this datapack!
