### ISSUE TITLE
Issue with Farmer's Delight Refabricated: Cutting Board recipes don't have the correct tool

### ISSUE THREAD

**Issue by megatrook** [22858/ns-fd-rc#2]
examples:
![image](https://github.com/22858/ns-fd-rc/assets/77197776/eee51b0b-ca67-4cbd-8add-4d6226df1f8e)
![image](https://github.com/22858/ns-fd-rc/assets/77197776/cf53e780-b5bb-4bb0-bd99-9d274dd15a0e)
![image](https://github.com/22858/ns-fd-rc/assets/77197776/ff93dcba-7aee-4bc4-8ab6-5f0d92b2c4bf)

**Comment by 22858** [comment]
Done. You can now check it out on Modrinth. 
Sorry for replying after such a long time😭

**Comment by megatrook** [comment]
no problem, thank you for the fix <3
